### ISSUE TITLE
print vs puts

### ISSUE THREAD

**Issue by thomashines** [learn-co-curriculum/interpolation-super-power#15]
This lab requires a nuanced knowledge of the difference between print and puts to pass, however, the curriculum is not very thorough at prepping for this. The clue that puts is the solution is \n added to the end of the error code, if one happens to fail by opting for print instead. This clue is searchable, the answer is obtainable, but why make it difficult and frustrating? Searching Google for what one doesn't know is sub-optimal knowledge acquisition. There's no reason why a student can't be completely found while performing a lab like this. I still fail to understand the implications of puts over print in this context, in a fluent, usable way, and that seems like a missed opportunity. If this depth of knowledge is not important yet, why allow one to fail over the other? For those who might opt to use print, the spotlight is immediately off of interpolation.

**Comment by cjbrock** [comment]
Hi @thomashines!
You definitely could use print in this lesson. However, since all of the example code uses puts, having even more information about puts vs print would complicate the lesson and take the focus off of string interpolation. Our goal is never to make the lessons difficult and frustrating, and I'm sorry that was your experience with this lesson. Part of becoming a developer is learning to ask questions and improving your Google skills, but you also always have the technical coaches at Ask A Question as backup if you need them! They are always happy to help.
--Corinna

**Comment by TyJaYo** [comment]
@cjbrock `print` might never be used for the output in the examples, but the word is used about 20 times in other ways throughout the instructions. You can see how it might be priming learners to fail if they see things like "`#display_rainbow` should print out the colors..." and "...to print them in alphabetical order...", especially if they haven't yet mastered the distinction between these two commands.

**Comment by TyJaYo** [comment]
@cjbrock incidentally, `p` doesn't work either—which is even more difficult for a beginner to debug. Here's the useful part of the error message received when an otherwise legitimate method uses `p` instead of `puts`:
> ```
> expected block to output 
> "R: red, O: orange, Y: yellow, G: green, B: blue, I: indigo, V: violet\n" to stdout, but output 
> "\"R: red, O: orange, Y: yellow, G: green, B: blue, I: indigo, V: violet\"\n"
> ```
> (added line breaks to aid visual comparison)

I was staring at that for a long time trying to figure out how I was supposed to pass a string without its surrounding quotation marks.
