### ISSUE TITLE
Correct Code Failed - Removing Default Argument Passed

### ISSUE THREAD

**Issue by CallieCoder** [learn-co-curriculum/interpolation-super-power#22]
The correct code pasted below did NOT work, and returned a failure: "spec ./spec/say_hello_spec.rb:10 # say_hello defaults to Ruby Programmer when no name is passed in..." (the rest was cut off from my 'Ask a Question').

def say_hello(name="Ruby Programmer")
  puts "Hello #{name}!"
end

When I deleted the default argument, the code passed. 
def say_hello(name)
  puts "Hello #{name}!"
end
say_hello

Please fix the instructions, which require the inclusion of a default argument. I wasted valuable and unnecessary time trying to figure out how my correct code was wrong, which is VERY frustrating!! The "Ask a Question" rep was also very baffled as to how this happened.

**Comment by drakeltheryuujin** [comment]
Hi @CallieCoder,

Thank you for spotting this issue and providing feedback.
We apologize for any frustration you might have encountered during this process
but I am not locating the issue that you're referencing. 

Is this issue raised in the correct lesson? This lab only has the file `./spec/display_rainbow_spec.rb` present, where 2 tests must be passed. Is [this lab](https://github.com/learn-co-curriculum/say-hello-ruby) where the issue is? 

Feel free to re-open this issue if I have misunderstood this request. Thanks!
